<a href="https://colab.research.google.com/github/isazadesabuhi/PyTorch_Tutorial/blob/main/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [4]:
my_list = [{1,3,5,6,8},{1,10,2,8,8}]
my_list

[{1, 3, 5, 6, 8}, {1, 2, 8, 10}]

In [ ]:
# Numpy Array
npm1 = np.random.rand(3,4)
npm1

In [74]:
# Tensor
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.7863, 0.7335, 0.6404, 0.2446],
        [0.6187, 0.2760, 0.8344, 0.7645],
        [0.9863, 0.8804, 0.2908, 0.9510]])

In [73]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [28]:
# creating tensor out of numpy array
my_tensor = torch.tensor(npm1)
my_tensor

tensor([[0.3154, 0.7462, 0.3766, 0.9620],
        [0.4257, 0.7725, 0.4020, 0.2645],
        [0.8616, 0.5074, 0.3588, 0.4381]], dtype=torch.float64)

In [29]:
# tensor operations
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [39]:
# reshape if we dont know the nb of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [41]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [66]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
my_torch7[7]

tensor(7)

In [68]:
# Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [69]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
# return column
my_torch8[:,1:]

TENSOR MATH OPERATIONS

In [88]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [89]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [97]:
# Addition LongHand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [78]:
# Substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [80]:
# Sub Function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [81]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [82]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [83]:
# Multiplication
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [90]:
# Div longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [91]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [92]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [94]:
# Exponenets / power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [106]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [111]:
tensor_a

tensor([11, 14, 17, 20])